# permissions for end users to edit peanutstages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: peanutstage-editor-role
rules:
- apiGroups:
  - pipeline.peanut.dev
  resources:
  - peanutstages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pipeline.peanut.dev
  resources:
  - peanutstages/status
  verbs:
  - get
