# permissions for end users to view peanutpipelineexecutions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: peanutpipelineexecution-viewer-role
rules:
- apiGroups:
  - pipeline.peanut.dev
  resources:
  - peanutpipelineexecutions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pipeline.peanut.dev
  resources:
  - peanutpipelineexecutions/status
  verbs:
  - get
