# permissions for end users to view peanutstages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: peanutstage-viewer-role
rules:
- apiGroups:
  - pipeline.peanut.dev
  resources:
  - peanutstages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pipeline.peanut.dev
  resources:
  - peanutstages/status
  verbs:
  - get
