
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
- apiGroups:
  - pipeline.peanut.dev
  resources:
  - peanutpipelineexecutions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pipeline.peanut.dev
  resources:
  - peanutpipelineexecutions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - pipeline.peanut.dev
  resources:
  - peanutpipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pipeline.peanut.dev
  resources:
  - peanutpipelines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - pipeline.peanut.dev
  resources:
  - peanutstages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pipeline.peanut.dev
  resources:
  - peanutstages/status
  verbs:
  - get
  - patch
  - update
